"""Add incentives

Revision ID: 0b688ec4a822
Revises: a4a84a67630b
Create Date: 2026-07-02 15:34:57.140358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b688ec4a822'
down_revision = 'a4a84a67630b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_annotators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('has_star', sa.Boolean(), nullable=True),
    sa.Column('form_submitted', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('parents_language', sa.String(length=100), nullable=True),
    sa.Column('stayed_outside', sa.Boolean(), nullable=True),
    sa.Column('stayed_outside_duration', sa.String(length=100), nullable=True),
    sa.Column('stayed_outside_purpose', sa.String(length=200), nullable=True),
    sa.Column('exposure', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'annotator_id', name='uq_campaign_annotator')
    )
    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_annotators_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_annotators_campaign_id'), ['campaign_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incentive_co_authorship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('incentive_money', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('incentive_min_wage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incentive_target_tasks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incentive_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incentive_intensity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incentive_bonus_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('incentive_bonus_amount')
        batch_op.drop_column('incentive_intensity')
        batch_op.drop_column('incentive_level')
        batch_op.drop_column('incentive_target_tasks')
        batch_op.drop_column('incentive_min_wage')
        batch_op.drop_column('incentive_money')
        batch_op.drop_column('incentive_co_authorship')

    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_annotators_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_annotators_annotator_id'))

    op.drop_table('campaign_annotators')
    # ### end Alembic commands ###
