"""Add campaign_id to qualification_tests

Revision ID: 202e0743e4cc
Revises: a7b31fd81eb8
Create Date: 2026-07-07 05:36:56.405609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202e0743e4cc'
down_revision = 'a7b31fd81eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_qualification_tests_campaign_id'), ['campaign_id'], unique=True)
        batch_op.create_foreign_key(None, 'campaigns', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_qualification_tests_campaign_id'))
        batch_op.drop_column('campaign_id')

    # ### end Alembic commands ###
