"""rename retry_cooldown_hours to retry_cooldown_minutes

Revision ID: 316f2948b73d
Revises: d88b089f8476
Create Date: 2026-07-05 22:06:52.785311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316f2948b73d'
down_revision = 'd88b089f8476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_cooldown_minutes', sa.Integer(), nullable=True))
        batch_op.drop_column('retry_cooldown_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_cooldown_hours', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('retry_cooldown_minutes')

    # ### end Alembic commands ###
