"""Add qualification status to campaign_annotators

Revision ID: 900c4b76f4cf
Revises: 202e0743e4cc
Create Date: 2026-07-07 05:55:17.996636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900c4b76f4cf'
down_revision = '202e0743e4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('qualified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.drop_column('qualified_at')
        batch_op.drop_column('qualification_status')

    # ### end Alembic commands ###
