"""Initial schema

Revision ID: a4a84a67630b
Revises: 
Create Date: 2026-07-01 16:19:28.883123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a84a67630b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_hash', sa.String(length=200), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('annotators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('otp_hash', sa.String(length=200), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('native_language', sa.String(length=100), nullable=True),
    sa.Column('expertise', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotators_email'), ['email'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_language', sa.String(length=100), nullable=False),
    sa.Column('target_language', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=True),
    sa.Column('input_label', sa.String(length=80), nullable=True),
    sa.Column('output_label', sa.String(length=80), nullable=True),
    sa.Column('difficulty_method', sa.String(length=20), nullable=True),
    sa.Column('difficulty_easy_max', sa.Integer(), nullable=True),
    sa.Column('difficulty_hard_min', sa.Integer(), nullable=True),
    sa.Column('served_difficulties', sa.String(length=50), nullable=True),
    sa.Column('expertise_matching', sa.Boolean(), nullable=True),
    sa.Column('rating_position', sa.String(length=10), nullable=True),
    sa.Column('span_position', sa.String(length=10), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('segments_json', sa.Text(), nullable=False),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('span_instructions', sa.Text(), nullable=True),
    sa.Column('span_scope', sa.String(length=20), nullable=True),
    sa.Column('enable_spans', sa.Boolean(), nullable=True),
    sa.Column('segments_per_page', sa.Integer(), nullable=True),
    sa.Column('eval_mode', sa.String(length=20), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.Column('scale_type', sa.String(length=20), nullable=True),
    sa.Column('scale_points', sa.Integer(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('scale_design', sa.String(length=20), nullable=True),
    sa.Column('scale_labels_json', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=200), nullable=True),
    sa.Column('drive_last_status', sa.String(length=20), nullable=True),
    sa.Column('drive_last_error', sa.Text(), nullable=True),
    sa.Column('drive_last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('results_snapshot_json', sa.Text(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_ab_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_ab_fraction', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=40), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_base_url', sa.String(length=300), nullable=True),
    sa.Column('ai_api_key_enc', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=True),
    sa.Column('segment_id', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_logs_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_logs_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=200), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('spans_json', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('preference', sa.String(length=100), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'annotator_id', 'segment_id', name='uq_campaign_annotator_segment')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_segment_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_annotator_id'))

    op.drop_table('ratings')
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_logs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_logs_annotator_id'))

    op.drop_table('assistant_logs')
    op.drop_table('campaigns')
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotators_email'))

    op.drop_table('annotators')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
