"""Add email_verified to annotators

Revision ID: d88b089f8476
Revises: e1d1c9eb6ce9
Create Date: 2026-07-05 17:19:22.946946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88b089f8476'
down_revision = 'e1d1c9eb6ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
