"""Add qualification feature

Revision ID: e1d1c9eb6ce9
Revises: 30a2c45ae165
Create Date: 2026-07-04 22:41:48.046891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d1c9eb6ce9'
down_revision = '30a2c45ae165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualification_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_cooldown_hours', sa.Integer(), nullable=True),
    sa.Column('eval_mode', sa.String(length=20), nullable=False),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualification_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['qualification_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_attempts_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualification_attempts_test_id'), ['test_id'], unique=False)

    op.create_table('qualification_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('target_a', sa.Text(), nullable=True),
    sa.Column('target_b', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('gold_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['qualification_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_segments_test_id'), ['test_id'], unique=False)

    op.create_table('qualification_responses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['qualification_attempts.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['qualification_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_responses_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualification_responses_segment_id'), ['segment_id'], unique=False)

    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('qualified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.drop_column('qualified_at')
        batch_op.drop_column('qualification_status')

    with op.batch_alter_table('qualification_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_responses_segment_id'))
        batch_op.drop_index(batch_op.f('ix_qualification_responses_attempt_id'))

    op.drop_table('qualification_responses')
    with op.batch_alter_table('qualification_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_segments_test_id'))

    op.drop_table('qualification_segments')
    with op.batch_alter_table('qualification_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_attempts_test_id'))
        batch_op.drop_index(batch_op.f('ix_qualification_attempts_annotator_id'))

    op.drop_table('qualification_attempts')
    op.drop_table('qualification_tests')
    # ### end Alembic commands ###
