"""Initial schema

Revision ID: f2345a55758b
Revises: 
Create Date: 2026-07-07 17:38:26.547818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2345a55758b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('otp_hash', sa.String(length=200), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('annotators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('otp_hash', sa.String(length=200), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('native_language', sa.String(length=100), nullable=True),
    sa.Column('expertise', sa.String(length=20), nullable=True),
    sa.Column('source_fluency', sa.String(length=20), nullable=True),
    sa.Column('target_fluency', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('dialect', sa.String(length=120), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('qualification_status', sa.String(length=20), nullable=False),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotators_email'), ['email'], unique=True)

    op.create_table('campaign_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_language', sa.String(length=100), nullable=False),
    sa.Column('target_language', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=True),
    sa.Column('input_label', sa.String(length=80), nullable=True),
    sa.Column('output_label', sa.String(length=80), nullable=True),
    sa.Column('difficulty_method', sa.String(length=20), nullable=True),
    sa.Column('difficulty_easy_max', sa.Integer(), nullable=True),
    sa.Column('difficulty_hard_min', sa.Integer(), nullable=True),
    sa.Column('served_difficulties', sa.String(length=50), nullable=True),
    sa.Column('expertise_matching', sa.Boolean(), nullable=True),
    sa.Column('rating_position', sa.String(length=10), nullable=True),
    sa.Column('span_position', sa.String(length=10), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('group_id', sa.String(length=32), nullable=True),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('source_script', sa.String(length=50), nullable=True),
    sa.Column('target_script', sa.String(length=50), nullable=True),
    sa.Column('segments_json', sa.Text(), nullable=False),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('span_instructions', sa.Text(), nullable=True),
    sa.Column('span_scope', sa.String(length=20), nullable=True),
    sa.Column('enable_spans', sa.Boolean(), nullable=True),
    sa.Column('segments_per_page', sa.Integer(), nullable=True),
    sa.Column('min_segments_per_page', sa.Integer(), nullable=True),
    sa.Column('max_segments_per_page', sa.Integer(), nullable=True),
    sa.Column('shuffle_segments', sa.Boolean(), nullable=True),
    sa.Column('eval_mode', sa.String(length=20), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.Column('scale_type', sa.String(length=20), nullable=True),
    sa.Column('scale_points', sa.Integer(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('scale_design', sa.String(length=20), nullable=True),
    sa.Column('scale_labels_json', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=200), nullable=True),
    sa.Column('drive_last_status', sa.String(length=20), nullable=True),
    sa.Column('drive_last_error', sa.Text(), nullable=True),
    sa.Column('drive_last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('results_snapshot_json', sa.Text(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_ab_enabled', sa.Boolean(), nullable=True),
    sa.Column('ai_ab_fraction', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=40), nullable=True),
    sa.Column('ai_model', sa.String(length=120), nullable=True),
    sa.Column('ai_base_url', sa.String(length=300), nullable=True),
    sa.Column('ai_api_key_enc', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('incentive_co_authorship', sa.Boolean(), nullable=True),
    sa.Column('incentive_money', sa.Boolean(), nullable=True),
    sa.Column('incentive_min_wage', sa.Float(), nullable=True),
    sa.Column('incentive_target_tasks', sa.Integer(), nullable=True),
    sa.Column('incentive_level', sa.Float(), nullable=True),
    sa.Column('incentive_intensity', sa.Float(), nullable=True),
    sa.Column('incentive_bonus_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['campaign_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_group_id'), ['group_id'], unique=False)

    op.create_table('annotator_campaign_prefs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('segments_per_page', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotator_id', 'campaign_id', name='uq_annotator_campaign_pref')
    )
    with op.batch_alter_table('annotator_campaign_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotator_campaign_prefs_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotator_campaign_prefs_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('assistant_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=True),
    sa.Column('segment_id', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_logs_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_logs_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_annotators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('has_star', sa.Boolean(), nullable=True),
    sa.Column('form_submitted', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('parents_language', sa.String(length=100), nullable=True),
    sa.Column('stayed_outside', sa.Boolean(), nullable=True),
    sa.Column('stayed_outside_duration', sa.String(length=100), nullable=True),
    sa.Column('stayed_outside_purpose', sa.String(length=200), nullable=True),
    sa.Column('exposure', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'annotator_id', name='uq_campaign_annotator')
    )
    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_annotators_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_annotators_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('qualification_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('eval_mode', sa.String(length=20), nullable=False),
    sa.Column('criteria_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_tests_campaign_id'), ['campaign_id'], unique=True)

    op.create_table('ratings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=200), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('spans_json', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('preference', sa.String(length=100), nullable=True),
    sa.Column('ranking_json', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'annotator_id', 'segment_id', name='uq_campaign_annotator_segment')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_segment_id'), ['segment_id'], unique=False)

    op.create_table('qualification_attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('annotator_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['qualification_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_attempts_annotator_id'), ['annotator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualification_attempts_test_id'), ['test_id'], unique=False)

    op.create_table('qualification_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('test_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('target_a', sa.Text(), nullable=True),
    sa.Column('target_b', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('gold_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['qualification_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_segments_test_id'), ['test_id'], unique=False)

    op.create_table('qualification_responses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['qualification_attempts.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['qualification_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualification_responses_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qualification_responses_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_responses_segment_id'))
        batch_op.drop_index(batch_op.f('ix_qualification_responses_attempt_id'))

    op.drop_table('qualification_responses')
    with op.batch_alter_table('qualification_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_segments_test_id'))

    op.drop_table('qualification_segments')
    with op.batch_alter_table('qualification_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_attempts_test_id'))
        batch_op.drop_index(batch_op.f('ix_qualification_attempts_annotator_id'))

    op.drop_table('qualification_attempts')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_segment_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_annotator_id'))

    op.drop_table('ratings')
    with op.batch_alter_table('qualification_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualification_tests_campaign_id'))

    op.drop_table('qualification_tests')
    with op.batch_alter_table('campaign_annotators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_annotators_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_annotators_annotator_id'))

    op.drop_table('campaign_annotators')
    with op.batch_alter_table('assistant_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_logs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_logs_annotator_id'))

    op.drop_table('assistant_logs')
    with op.batch_alter_table('annotator_campaign_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotator_campaign_prefs_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_annotator_campaign_prefs_annotator_id'))

    op.drop_table('annotator_campaign_prefs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_group_id'))

    op.drop_table('campaigns')
    op.drop_table('campaign_groups')
    with op.batch_alter_table('annotators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotators_email'))

    op.drop_table('annotators')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
